/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#001a42',
        'navy-deep': '#0B132B',
        'on-primary-container': '#7c839b',
        'surface-dim': '#cbdbf5',
        'on-primary': '#ffffff',
        'inverse-primary': '#bec6e0',
        'secondary': '#0051d5',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fefcff',
        'primary-fixed': '#dae2fd',
        'text-tertiary': '#94A3B8',
        'background': '#f8f9ff',
        'on-surface': '#0b1c30',
        'card-bg': '#FFFFFF',
        'inverse-surface': '#213145',
        'surface-variant': '#d3e4fe',
        'on-primary-fixed': '#131b2e',
        'tertiary-fixed': '#d8e2ff',
        'on-error-container': '#93000a',
        'on-tertiary': '#ffffff',
        'surface-container-low': '#eff4ff',
        'risk-high-subtle': '#FFFBEB',
        'secondary-fixed-dim': '#b4c5ff',
        'on-surface-variant': '#45464d',
        'surface': '#f8f9ff',
        'surface-tint': '#565e74',
        'on-background': '#0b1c30',
        'risk-medium-subtle': '#FEFCE8',
        'primary-container': '#131b2e',
        'secondary-container': '#316bf3',
        'error': '#ba1a1a',
        'risk-low-subtle': '#ECFDF5',
        'border-subtle': '#CBD5E1',
        'on-secondary-fixed': '#00174b',
        'surface-container-highest': '#d3e4fe',
        'outline': '#76777d',
        'surface-container': '#e5eeff',
        'risk-medium': '#EAB308',
        'on-primary-fixed-variant': '#3f465c',
        'surface-container-lowest': '#ffffff',
        'tertiary': '#000000',
        'primary': '#000000',
        'risk-critical': '#EF4444',
        'tertiary-fixed-dim': '#adc6ff',
        'surface-bg': '#F8FAFC',
        'on-tertiary-container': '#3980f4',
        'text-primary': '#0F172A',
        'on-tertiary-fixed-variant': '#004395',
        'risk-low': '#10B981',
        'navy-surface': '#1C2541',
        'risk-high': '#F59E0B',
        'border-hairline': '#E2E8F0',
        'surface-bright': '#f8f9ff',
        'outline-variant': '#c6c6cd',
        'surface-container-high': '#dce9ff',
        'on-tertiary-fixed': '#001a42',
        'primary-fixed-dim': '#bec6e0',
        'risk-critical-subtle': '#FEF2F2',
        'secondary-fixed': '#dbe1ff',
        'text-secondary': '#475569',
        'on-secondary-fixed-variant': '#003ea8',
        'inverse-on-surface': '#eaf1ff',
        'error-container': '#ffdad6',
        'on-error': '#ffffff'
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px'
      },
      spacing: {
        'kpi-grid-gutter': '0.625rem',
        'unit-lg': '1rem',
        'unit-md': '0.75rem',
        'unit-xs': '0.25rem',
        'card-padding-mobile': '1rem',
        'unit-xl': '1.25rem',
        'unit-3xl': '2rem',
        'unit-sm': '0.5rem',
        'unit-2xl': '1.5rem',
        'unit-2xs': '0.125rem',
        'card-gap-mobile': '0.75rem',
        'screen-edge-mobile': '1rem'
      },
      fontFamily: {
        'display-lg': ['var(--font-plus-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['var(--font-plus-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        'kpi-value': ['var(--font-plus-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        'numeric-mono': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'body-sm': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'headline-lg': ['var(--font-plus-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['var(--font-plus-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'label-md': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'Inter', 'sans-serif']
      },
      fontSize: {
        'display-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-sm': ['15px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'kpi-value': ['26px', { lineHeight: '30px', letterSpacing: '-0.025em', fontWeight: '800' }],
        'numeric-mono': ['12px', { lineHeight: '16px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'body-lg': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-lg': ['22px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['18px', { lineHeight: '24px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'label-sm': ['10px', { lineHeight: '12px', letterSpacing: '0.06em', fontWeight: '700' }],
        'label-md': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        'body-md': ['13px', { lineHeight: '18px', fontWeight: '400' }]
      }
    },
  },
  plugins: [],
}
